repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        args: [--exclude='^docker/']
        language: system
        types:
          - python
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types:
          - python
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types:
          - python
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types:
          - python
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types:
          - python
        exclude: tests/*